services:
  - type: web
    name: grok-t
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance
      python -c "from app import db, app; app.app_context().push(); db.create_all(); from app import init_db; init_db()"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/lms.db
    healthCheckPath: /health
    autoDeploy: true
    plan: free 